all:
	njsc -exe print.njs print	
	njsc -exe testDeepCopy.njs testDeepCopy
	njsc -exe hanoi.njs hanoi
	njsc -exe testcommon.njs testcommon
	njsc -exe sort.njs sort
clean:
	rm -f print sort testDeepCopy hanoi testcommon
